baseURL = 'https://docs.mor-gan.com/'
languageCode = 'en-us'
title = 'morgan docs'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
    unsafe = true

